name = "startest"
version = "0.1.0"
description = "A testing framework to help you shoot for the stars"
licenses = ["MIT"]
repository = { type = "github", user = "maxdeviant", repo = "startest" }

[dependencies]
exception = ">= 2.0.0 and < 3.0.0"
gleam_community_ansi = ">= 1.4.0 and < 2.0.0"
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
simplifile = ">= 1.7.0 and < 2.0.0"

[dev-dependencies]
